version: '3.8'

services:
  postgres:
    image: postgres:latest
    platform: linux/x86_64
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - 'odoo-db-data:/var/lib/postgresql/data/pgdata'
    ports:
      - ${POSTGRES_EXPOSE_PORT}:5432

  web:
    image: odoo:16
    platform: linux/x86_64
    depends_on:
      - postgres
    ports:
      - ${ODOO_EXPOSE_PORT}:8069
    environment:
      - HOST=postgres
      - USER=${POSTGRES_USER}
      - PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - 'odoo-web-data:/var/lib/odoo'
      - './config/odoo:/etc/odoo'
      - './addons/odoo:/mnt/extra-addons'

networks:
  odoo_docker:
    name: odoo_docker
    driver: bridge

volumes:
  odoo-web-data:
  odoo-db-data:
